[versions]
annotation = "1.2.0-beta01"
appcompat = "1.3.0-beta01"
constraintlayout = "2.0.4"
core-ktx = "1.3.2"
preference-ktx = "1.1.1"
robolectricVersion = "4.9.2"

[libraries]
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preference-ktx" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectricVersion" }

[plugins]

