[versions]
annotation = "1.2.0-beta01"
appcompat = "1.3.0-beta01"
core-ktx = "1.3.2"

[libraries]
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }

[plugins]

