name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Make dummy gradle.properties
      run: |
        chmod +x app/make_plain_gradle_properties.sh
        cd app
        ./make_plain_gradle_properties.sh
        cd -

    # Dependency Graph
    - name: Setup Graphviz environment
      uses: kamiazya/setup-graphviz@v1

    - name: Generate Dependency Graph
      run: ./gradlew projectDependencyGraph

    - name: Upload Dependency Graph
      uses: actions/upload-artifact@v2
      with:
        name: Dependency Graph
        path: build/reports/dependency-graph/project.dot.png

    # Generates a debug APK
    - name: Build debug version with Gradle
      run: ./gradlew assembleQuad5Debug

    - name: Unit Test
      run: ./gradlew test
