name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: set up JDK 8, 11, 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: |
          8
          11
          17
        cache: gradle

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Setup Gradle Cacge
      uses: gradle/gradle-build-action@v3

    - name: Make dummy gradle.properties
      run: (cd app; ./make_plain_gradle_properties.sh)

    - name: Build debug version with Gradle
      run: ./gradlew assembleQuad5Debug

    - name: Unit Test
      run: ./gradlew test
